### Create a new category
POST https://flownow.agnieve.com/api/categories
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3NDI3Mzg1NDF9.AYrruQrMFoLtSeQnPIHM9EuCJ0SLUItfZYRIgcW_UQQ

{
    "name": "Meditation"
}

### Get all categories
GET https://flownow.agnieve.com/api/categories
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3NDI3Mzg1NDF9.AYrruQrMFoLtSeQnPIHM9EuCJ0SLUItfZYRIgcW_UQQ

### Get a specific category
GET https://flownow.agnieve.com/api/categories/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3NDI3Mzg1NDF9.AYrruQrMFoLtSeQnPIHM9EuCJ0SLUItfZYRIgcW_UQQ

### Update a category
PUT https://flownow.agnieve.com/api/categories/2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3NDI3Mzg1NDF9.AYrruQrMFoLtSeQnPIHM9EuCJ0SLUItfZYRIgcW_UQQ

{
    "name": "Updated Meditation",
    "description": "Updated meditation practices description"
}

### Delete a category
DELETE https://flownow.agnieve.com/api/categories/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3NDI3Mzg1NDF9.AYrruQrMFoLtSeQnPIHM9EuCJ0SLUItfZYRIgcW_UQQ