### Login user (HTTP Only Cookie)
# POST http://localhost:3005/auth/login
POST https://flownow.agnieve.com/auth/login
Content-Type: application/json

{
    "email": "dev@agnieve.com",
    "password": "pass123"
}

### Register a new user
POST https://flownow.agnieve.com/register
Content-Type: application/json

{
    "email": "dev@agnieve.com",
    "password": "pass123",
    "name": "AG Nieve",
    "role": "admin",
    "status": "active",
    "plan": "free"
}


### Get all users
GET https://flownow.agnieve.com/users
# GET http://localhost:3005/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21lb25lIiwiY29tcGFueSI6IjEiLCJleHAiOjE3NDI4MDE0NjR9.T1OQWQb_K3yuDkfIBOK8kbuIPDT_Vw65MvfqRMdQtS4

### Get single user
GET http://localhost:3005/users/1
Content-Type: application/json

### Update user
PUT http://localhost:3005/users/1
Content-Type: application/json

{
    "first_name": "Updated",
    "last_name": "Name",
    "email": "updated@example.com"
}

### Delete user
DELETE http://localhost:3005/users/1
Content-Type: application/json

### Logout user
POST http://localhost:3005/auth/logout
Content-Type: application/json